### ISSUE TITLE
Switch from Travis

### ISSUE THREAD

**Issue by kibertoad** [PayU/api-contract-validator#47]
Travis CI seems to be malfunctioning again.

Maybe we want to move to CircleCI or GitHub actions?

**Comment by kibertoad** [comment]
@kobik I can prepare a PR if you see benefit in this (will need to be enabled from CI provider side as well by repo admin as well, though).

**Comment by kobik** [comment]
Besides stability issues with travis, what are we losing or gaining by this move?

**Comment by kibertoad** [comment]
Losing - not aware of anything. Gaining - travis has unpleasant habit of back-queueing builds for projects that just had their builds triggered, so if there is plenty of PRs submitted on the same hour or if there are rebuilds triggered, sometimes there is an unfun waiting involved. Neither CircleCI, nor GA, to my knowledge, don't have that.

**Comment by kobik** [comment]
ok, lets go for it.

we can always switch back
